[package]
name = "notification"
version = "0.1.0"
edition = "2021"
description = "A Notification service that implement the org.freedesktop.Notifications interface"

[dependencies]
zbus = { version = "5.2.0", features = ["tokio"] }
tokio = { workspace = true }
