[package]
name = "battery"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = { version = "5.2.0", features = ["tokio"] }
serde_repr = "0.1.19"
serde = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
